var empleadosLista = [
  //CENTRAL
  {
    "nombre": "Maximiliano",
    "apellido": "Segovia",
    "dni": 31997465,
    "condicion": "Planta Permanente",
    "codigo": 11813,
    "movilidad": 0,
    "distancia": 1,
    "diasCorrespondientes": 15,
    "telefono": 3424237653,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/gTG8h14/foto-maxi.png",
  },
  {
    "nombre": "Jorge Adrián",
    "apellido": "Canteros",
    "dni": 34238376,
    "condicion": "Planta Permanente",
    "codigo": 13687,
    "movilidad": 1,
    "distancia": 1,
    "diasCorrespondientes": 20,
    "telefono": 3424473531,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/pZ162cJ/jorgecanteros.png",
  },
  {
    "nombre": "Santiago",
    "apellido": "Croppi",
    "dni": 35951931,
    "condicion": "Planta Permanente",
    "codigo": 13685,
    "movilidad": 1,
    "distancia": 0,
    "diasCorrespondientes": 20,
    "telefono": 3425386642,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/D9Zd6kc/croppi.png",
  },
  {
    "nombre": "Iván David",
    "apellido": "Mehaudy",
    "dni": 35650403,
    "condicion": "Contrato",
    "codigo": 10001,
    "movilidad": 0,
    "distancia": 1,
    "diasCorrespondientes": 10,
    "telefono": 3425929192,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/ZKXKq0k/foto-chica-ivan.png",
  },
  {
    "nombre": "María del Rosario",
    "apellido": "Alasio Garmendia",
    "dni": 33873039,
    "condicion": "Planta Permantente",
    "codigo": 14436,
    "movilidad": 1,
    "distancia": 0,
    "diasCorrespondientes": 20,
    "telefono": 3425124646,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Mariana Soledad",
    "apellido": "Barcos",
    "dni": 34716186,
    "condicion": "Planta Permantente",
    "codigo": 14428,
    "movilidad": 1,
    "distancia": 0,
    "diasCorrespondientes": 20,
    "telefono": 3425353101,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Erica",
    "apellido": "Sureda",
    "dni": 32701779,
    "condicion": "Planta Permantente",
    "codigo": 13695,
    "movilidad": true,
    "distancia": false,
    "diasCorrespondientes": 30,
    "telefono": 3425276987,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Celia",
    "apellido": "Leguizamón",
    "dni": 20806869,
    "condicion": "Planta Permantente",
    "codigo": 14767,
    "movilidad": true,
    "distancia": false,
    "diasCorrespondientes": 25,
    "telefono": 3424092385,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "María Magdalena",
    "apellido": "Guerreño",
    "dni": 22136633,
    "condicion": "Planta No Permantente",
    "codigo": 15633,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 10,
    "telefono": 3426130191,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Andrea Jimena",
    "apellido": "Lechi",
    "dni": 32873927,
    "condicion": "Planta Permantente",
    "codigo": 14435,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 20,
    "telefono": 3425145522,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/Kx5hPDY/lechi-andrea.jpg",
  },
  {
    "nombre": "Soraya Rocío",
    "apellido": "Saade",
    "dni": 34163330,
    "condicion": "Planta Permantente",
    "codigo": 15117,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 20,
    "telefono": 3425163805,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/JKMkk6G/IMG-20220805-WA0006.jpg",
  },
  {
    "nombre": "Sandra Rita",
    "apellido": "Muzycka",
    "dni": 29618889,
    "condicion": "Planta Permantente",
    "codigo": 14715,
    "movilidad": true,
    "distancia": true,
    "diasCorrespondientes": 20,
    "telefono": 3425327129,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Estefanía",
    "apellido": "Olivero",
    "dni": 0,
    "condicion": "Planta Permantente",
    "codigo": 14427,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 20,
    "telefono": 3425054451,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Fabio",
    "apellido": "Ferraro",
    "dni": 0,
    "condicion": "Contrato",
    "codigo": 0,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 10,
    "telefono": 3425150210,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Alexis Gastón",
    "apellido": "Bravo",
    "dni": 34301652,
    "condicion": "Planta No Permantente",
    "codigo": 15710,
    "movilidad": true,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425107360,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Jesica",
    "apellido": "Rodriguez",
    "dni": 34745775,
    "condicion": "Planta Permantente",
    "codigo": 13693,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 20,
    "telefono": 3404534406,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "María Eugenia",
    "apellido": "Demiryi",
    "dni": 13190283,
    "condicion": "Planta Permantente",
    "codigo": 10603,
    "movilidad": true,
    "distancia": false,
    "diasCorrespondientes": 30,
    "telefono": 3424369903,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Susana Griselda",
    "apellido": "Mosqueira",
    "dni": 18096223,
    "condicion": "Practicante",
    "codigo": 63634,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 10,
    "telefono": 3424486609,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Mónica Patricia",
    "apellido": "Reinoso",
    "dni": 35127726,
    "condicion": "Practicante",
    "codigo": 64747,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425374540,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Leonel",
    "apellido": "Milessi",
    "dni": 39632074,
    "condicion": "Practicante",
    "codigo": 65101,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 10,
    "telefono": 3424362166,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Jonatan Exequiel",
    "apellido": "Córdoba",
    "dni": 35120614,
    "condicion": "Practicante",
    "codigo": 65052,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 10,
    "telefono": 3425167632,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Melisa",
    "apellido": "Martínez",
    "dni": 2,
    "condicion": "Planta Permantente",
    "codigo": 13158,
    "movilidad": true,
    "distancia": false,
    "diasCorrespondientes": 20,
    "telefono": 3425338137,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Maira Nerea",
    "apellido": "Gorría",
    "dni": 2,
    "condicion": "Planta Permantente",
    "codigo": 12885,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 20,
    "telefono": 3425165158,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Natán",
    "apellido": "Piríz",
    "dni": 2,
    "condicion": "Planta Permantente",
    "codigo": 14302,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 20,
    "telefono": 3425323894,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Lucio Octavio",
    "apellido": "Sampietro",
    "dni": 37571497,
    "condicion": "Practicante",
    "codigo": 65071,
    "movilidad": true,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3424469904,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  // VILLA TERESA
  {
    "nombre": "Estefanía",
    "apellido": "Bogner",
    "dni": 34959595,
    "condicion": "Planta Permanente",
    "codigo": 62151,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 20,
    "telefono": 342659994,
    "estacion": 'Villa Teresa',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },

  // MEDIATECA
  {
    "nombre": "Alicia",
    "apellido": "Machado",
    "dni": 0,
    "condicion": "Planta No Permanente",
    "codigo": 15625,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3426987758,
    "estacion": 'Mediateca Santa Rosa',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Daiana",
    "apellido": "Morales",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 64790,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425167730,
    "estacion": 'Mediateca Santa Rosa',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Rocío",
    "apellido": "Ruíz",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 65289,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 342508859,
    "estacion": 'Mediateca Santa Rosa',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Walter",
    "apellido": "Maik",
    "dni": 0,
    "condicion": "Planta Permantente",
    "codigo": 40050,
    "movilidad": true,
    "distancia": true,
    "diasCorrespondientes": 30,
    "telefono": 3425419899,
    "estacion": 'Mediateca Santa Rosa',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "María de los Ángeles",
    "apellido": "Leiva",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 64898,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425220646,
    "estacion": 'Mediateca Santa Rosa',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },

  // BARRANQUITAS

  {
    "nombre": "Mercedes",
    "apellido": "Fernandez",
    "dni": 0,
    "condicion": "Planta Permantente",
    "codigo": 64790,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425167730,
    "estacion": 'Barranquitas',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Natalia",
    "apellido": "Rodríguez",
    "dni": 0,
    "condicion": "Planta No Permantente",
    "codigo": 15623,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425998619,
    "estacion": 'Barranquitas',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Ivana",
    "apellido": "Ríos",
    "dni": 0,
    "condicion": "Planta No Permantente",
    "codigo": 15621,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3426336821,
    "estacion": 'Barranquitas',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Rocío",
    "apellido": "Zimmerman",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 65287,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3424323237,
    "estacion": 'Barranquitas',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Roberto",
    "apellido": "Barrios",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 65278,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425933301,
    "estacion": 'Barranquitas',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Inés",
    "apellido": "Acosta",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 65203,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425041543,
    "estacion": 'Barranquitas',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Jackeline",
    "apellido": "Quintero",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 65134,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425082537,
    "estacion": 'Barranquitas',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Belén",
    "apellido": "Barreto",
    "dni": 0,
    "condicion": "Contrato",
    "codigo": 65203,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3424449595,
    "estacion": 'Barranquitas',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Marianela",
    "apellido": "Moretti",
    "dni": 0,
    "condicion": "Contrato",
    "codigo": 0,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3424721361,
    "estacion": 'Barranquitas',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Milagros",
    "apellido": "Masjoan",
    "dni": 0,
    "condicion": "Planta Permantente",
    "codigo": 15120,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 15,
    "telefono": 3425046228,
    "estacion": 'Barranquitas',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },

  // ABASTO

  {
    "nombre": "María Alicia",
    "apellido": "Garzón",
    "dni": 0,
    "condicion": "Contrato",
    "codigo": 0,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 0,
    "estacion": 'Abasto',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Victoria",
    "apellido": "Acevedo",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 63384,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3424368143,
    "estacion": 'Abasto',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Patricia",
    "apellido": "Acosta",
    "dni": 0,
    "condicion": "Planta Permanente",
    "codigo": 15170,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 20,
    "telefono": 3425004771,
    "estacion": 'Abasto',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Alejandro",
    "apellido": "Alessandria",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 65284,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3424232432,
    "estacion": 'Abasto',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "María Ángeles",
    "apellido": "Chesi",
    "dni": 0,
    "condicion": "64784",
    "codigo": 63384,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425102421,
    "estacion": 'Abasto',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Oscar",
    "apellido": "Duarte",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 61051,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425993017,
    "estacion": 'Abasto',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Rocío",
    "apellido": "Godoy",
    "dni": 0,
    "condicion": "Contrato",
    "codigo": 0,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425490712,
    "estacion": 'Abasto',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Yamila",
    "apellido": "Paye",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 63557,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425562154,
    "estacion": 'Abasto',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Romina",
    "apellido": "Sánchez",
    "dni": 0,
    "condicion": "Planta Permanente",
    "codigo": 15528,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 15,
    "telefono": 3426311938,
    "estacion": 'Abasto',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Marta",
    "apellido": "Sandoval",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 64786,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3424068576,
    "estacion": 'Abasto',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },

  // COLASTINÉ NORTE

  {
    "nombre": "Alejandra",
    "apellido": "Aguiar",
    "dni": 0,
    "condicion": "Planta Permanente",
    "codigo": 14866,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 20,
    "telefono": 3424870428,
    "estacion": 'Colastiné Norte',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Marcelo",
    "apellido": "Benegas",
    "dni": 0,
    "condicion": "Planta No Permanente",
    "codigo": 15632,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3424476702,
    "estacion": 'Colastiné Norte',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "María Paula",
    "apellido": "Guitart",
    "dni": 0,
    "condicion": "Planta Permanente",
    "codigo": 13686,
    "movilidad": true,
    "distancia": true,
    "diasCorrespondientes": 20,
    "telefono": 3424680929,
    "estacion": 'Colastiné Norte',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Alejandra Silvina",
    "apellido": "González",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 62206,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3424636717,
    "estacion": 'Colastiné Norte',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Daniela",
    "apellido": "Marano",
    "dni": 0,
    "condicion": "Planta Permanente",
    "codigo": 11236,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 25,
    "telefono": 3426316922,
    "estacion": 'Colastiné Norte',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Rosario",
    "apellido": "Perelló",
    "dni": 0,
    "condicion": "Planta Permanente",
    "codigo": 15167,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 20,
    "telefono": 3425579067,
    "estacion": 'Colastiné Norte',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Mariela",
    "apellido": "Vega",
    "dni": 0,
    "condicion": "Planta Permanente",
    "codigo": 13955,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 20,
    "telefono": 3426980252,
    "estacion": 'Colastiné Norte',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Ana Rosa",
    "apellido": "Cejas",
    "dni": 0,
    "condicion": "Planta Permanente",
    "codigo": 5682,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 30,
    "telefono": 0,
    "estacion": 'Colastiné Norte',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Daniela",
    "apellido": "Gramaglia",
    "dni": 0,
    "condicion": "Planta Permanente",
    "codigo": 12689,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 25,
    "telefono": 0,
    "estacion": 'Colastiné Norte',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Mariana",
    "apellido": "Martínez",
    "dni": 0,
    "condicion": "Planta Permanente",
    "codigo": 12692,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 20,
    "telefono": 0,
    "estacion": 'Colastiné Norte',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },

  // VARADERO SARSOTTI

  {
    "nombre": "Griselda",
    "apellido": "Romero",
    "dni": 0,
    "condicion": "Contrato",
    "codigo": 0,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 0,
    "estacion": 'Varadero Sarsotti',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Anabel",
    "apellido": "Argüello",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 0,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 0,
    "estacion": 'Varadero Sarsotti',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Patricia",
    "apellido": "Coccocioni",
    "dni": 0,
    "condicion": "Planta Permanente",
    "codigo": 13775,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 15,
    "telefono": 3425027631,
    "estacion": 'Varadero Sarsotti',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Leonel",
    "apellido": "Monges",
    "dni": 0,
    "condicion": "Planta Permanente",
    "codigo": 15161,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 15,
    "telefono": 3425027631,
    "estacion": 'Varadero Sarsotti',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Juliana",
    "apellido": "Pérez Knaupp",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 65281,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425590757,
    "estacion": 'Varadero Sarsotti',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Mariela",
    "apellido": "Portillo",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 62418,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425243546,
    "estacion": 'Varadero Sarsotti',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Mirta",
    "apellido": "Portillo",
    "dni": 0,
    "condicion": "Planta Permanente",
    "codigo": 14766,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 10,
    "telefono": 3424395442,
    "estacion": 'Varadero Sarsotti',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "María Sol",
    "apellido": "Rodrigo",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 64916,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425457047,
    "estacion": 'Varadero Sarsotti',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Luciana",
    "apellido": "Suárez",
    "dni": 0,
    "condicion": "Planta Permanente",
    "codigo": 14159,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3424411248,
    "estacion": 'Varadero Sarsotti',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
];
