var empleadosLista = [
  //CENTRAL
  {
    "nombre": "Maximiliano",
    "apellido": "Segovia",
    "dni": 31997465,
    "condicion": "Planta Permanente",
    "codigo": 11813,
    "movilidad": 0,
    "distancia": 1,
    "diasCorrespondientes": 15,
    "telefono": 3424237653,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/gTG8h14/foto-maxi.png",
  },
  {
    "nombre": "Jorge Adrián",
    "apellido": "Canteros",
    "dni": 34238376,
    "condicion": "Planta Permanente",
    "codigo": 13687,
    "movilidad": 1,
    "distancia": 1,
    "diasCorrespondientes": 20,
    "telefono": 3424473531,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/pZ162cJ/jorgecanteros.png",
  },
  {
    "nombre": "Santiago",
    "apellido": "Croppi",
    "dni": 35951931,
    "condicion": "Planta Permanente",
    //"codigo": 13685,
    "codigo": 99999,
    "movilidad": 1,
    "distancia": 0,
    "diasCorrespondientes": 20,
    "telefono": 3425386642,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/D9Zd6kc/croppi.png",
  },
  {
    "nombre": "Iván David",
    "apellido": "Mehaudy",
    "dni": 35650403,
    "condicion": "Contrato",
    "codigo": 10001,
    "movilidad": 0,
    "distancia": 1,
    "diasCorrespondientes": 10,
    "telefono": 3425929192,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/ZKXKq0k/foto-chica-ivan.png",
  },
  {
    "nombre": "María del Rosario",
    "apellido": "Alasio Garmendia",
    "dni": 33873039,
    "condicion": "Planta Permantente",
    "codigo": 14436,
    "movilidad": 1,
    "distancia": 0,
    "diasCorrespondientes": 20,
    "telefono": 3425124646,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Mariana Soledad",
    "apellido": "Barcos",
    "dni": 34716186,
    "condicion": "Planta Permantente",
    "codigo": 14428,
    "movilidad": 1,
    "distancia": 0,
    "diasCorrespondientes": 20,
    "telefono": 3425353101,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Erica",
    "apellido": "Sureda",
    "dni": 32701779,
    "condicion": "Planta Permantente",
    "codigo": 13695,
    "movilidad": true,
    "distancia": false,
    "diasCorrespondientes": 30,
    "telefono": 3425276987,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Celia",
    "apellido": "Leguizamón",
    "dni": 20806869,
    "condicion": "Planta Permantente",
    "codigo": 14767,
    "movilidad": true,
    "distancia": false,
    "diasCorrespondientes": 25,
    "telefono": 3424092385,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "María Magdalena",
    "apellido": "Guerreño",
    "dni": 22136633,
    "condicion": "Planta No Permantente",
    "codigo": 15633,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 10,
    "telefono": 3426130191,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Andrea Jimena",
    "apellido": "Lechi",
    "dni": 32873927,
    "condicion": "Planta Permantente",
    "codigo": 14435,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 20,
    "telefono": 3425145522,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/Kx5hPDY/lechi-andrea.jpg",
  },
  {
    "nombre": "Soraya Rocío",
    "apellido": "Saade",
    "dni": 34163330,
    "condicion": "Planta Permantente",
    "codigo": 15117,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 20,
    "telefono": 3425163805,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/JKMkk6G/IMG-20220805-WA0006.jpg",
  },
  {
    "nombre": "Sandra Rita",
    "apellido": "Muzycka",
    "dni": 29618889,
    "condicion": "Planta Permantente",
    "codigo": 14715,
    "movilidad": true,
    "distancia": true,
    "diasCorrespondientes": 20,
    "telefono": 3425327129,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Alexis Gastón",
    "apellido": "Bravo",
    "dni": 34301652,
    "condicion": "Planta No Permantente",
    "codigo": 15710,
    "movilidad": true,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425107360,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Jesica",
    "apellido": "Rodriguez",
    "dni": 34745775,
    "condicion": "Planta Permantente",
    "codigo": 13693,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 20,
    "telefono": 3404534406,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "María Eugenia",
    "apellido": "Demiryi",
    "dni": 13190283,
    "condicion": "Planta Permantente",
    "codigo": 10603,
    "movilidad": true,
    "distancia": false,
    "diasCorrespondientes": 30,
    "telefono": 3424369903,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Susana Griselda",
    "apellido": "Mosqueira",
    "dni": 18096223,
    "condicion": "Practicante",
    "codigo": 63634,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 10,
    "telefono": 3424486609,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Mónica Patricia",
    "apellido": "Reinoso",
    "dni": 35127726,
    "condicion": "Practicante",
    "codigo": 64747,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425374540,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Leonel",
    "apellido": "Milessi",
    "dni": 39632074,
    "condicion": "Practicante",
    "codigo": 65101,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 10,
    "telefono": 3424362166,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Jonatan Exequiel",
    "apellido": "Córdoba",
    "dni": 35120614,
    "condicion": "Practicante",
    "codigo": 65052,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 10,
    "telefono": 3425167632,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Melisa",
    "apellido": "Martínez",
    "dni": 2,
    "condicion": "Planta Permantente",
    "codigo": 13158,
    "movilidad": true,
    "distancia": false,
    "diasCorrespondientes": 20,
    "telefono": 3425338137,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Maira Nerea",
    "apellido": "Gorría",
    "dni": 2,
    "condicion": "Planta Permantente",
    "codigo": 12885,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 20,
    "telefono": 3425165158,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Natán",
    "apellido": "Piríz",
    "dni": 2,
    "condicion": "Planta Permantente",
    "codigo": 14302,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 20,
    "telefono": 3425323894,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Lucio Octavio",
    "apellido": "Sampietro",
    "dni": 37571497,
    "condicion": "Practicante",
    "codigo": 65071,
    "movilidad": true,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3424469904,
    "estacion": 'Central',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  // VILLA TERESA
  {
    "nombre": "Estefanía",
    "apellido": "Bogner",
    "dni": 34959595,
    "condicion": "Planta Permanente",
    "codigo": 62151,
    "movilidad": false,
    "distancia": false,
    "diasCorrespondientes": 20,
    "telefono": 342659994,
    "estacion": 'Villa Teresa',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },

  // MEDIATECA
  {
    "nombre": "Alicia",
    "apellido": "Machado",
    "dni": 0,
    "condicion": "Planta No Permanente",
    "codigo": 15625,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3426987758,
    "estacion": 'Mediateca Santa Rosa',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Daiana",
    "apellido": "Morales",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 64790,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425167730,
    "estacion": 'Mediateca Santa Rosa',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Rocío",
    "apellido": "Ruíz",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 65289,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 342508859,
    "estacion": 'Mediateca Santa Rosa',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "Walter",
    "apellido": "Maik",
    "dni": 0,
    "condicion": "Planta Permantente",
    "codigo": 40050,
    "movilidad": true,
    "distancia": true,
    "diasCorrespondientes": 30,
    "telefono": 3425419899,
    "estacion": 'Mediateca Santa Rosa',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
  {
    "nombre": "María de los Ángeles",
    "apellido": "Leiva",
    "dni": 0,
    "condicion": "Practicante",
    "codigo": 64898,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425220646,
    "estacion": 'Mediateca Santa Rosa',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },

  // BARRANQUITAS

  {
    "nombre": "Mercedes",
    "apellido": "Fernandez",
    "dni": 0,
    "condicion": "Planta Permantente",
    "codigo": 64790,
    "movilidad": false,
    "distancia": true,
    "diasCorrespondientes": 10,
    "telefono": 3425167730,
    "estacion": 'Barranquitas',
    "urlFoto": "https://i.ibb.co/XpVmDLL/empty.png",
  },
];
